### ISSUE TITLE
Use BCP-47 for language codes

### ISSUE THREAD

**Issue by ruphy** [italia/publiccode.yml#2]

**Comment by edent** [comment]
In the UK Government we prefer to use  ISO 639-1:2002.

See https://www.gov.uk/government/publications/open-standards-for-government/language-tags

Is there a good reason to prefer one over the other?

**Comment by ioggstream** [comment]
Hi @edent, thanks for your comment!

From the linked doc, I read:

  - in the `headline`: you have to use ISO 639-1:2002 
  - in the `Challenge`: you have to use [IANA Language Tag](https://www.w3.org/International/articles/language-tags/) registry which follows bcp-47 syntax

```
Standards to be used ISO 639-1:2002


1. Challenge
...
Government bodies must [...] use one of the codes cited in the IANA Language Tag registry,
 a superset of the ISO 639-1 (2002) language codes. 
   ^^^^^^^^^ iiuc that superset is BCP-47

``` 

Any hints?

**Comment by libremente** [comment]
Hi @edent, following @ioggstream reply, do you have any further hints regarding this matter? BCP-47 seems like a reasonable superset to me. Thanks!

**Comment by edent** [comment]
It does. Please ignore me 😊

**Comment by alranel** [comment]
I definitely agree with the switch to BCP47 because it accommodates for languages used by minorities, and this is relevant for public code in many countries.
It should be noted that this is a **breaking change** as we have been using the three letters version (es. `ita`, `eng`) so we'll have to make our parsers tolerant to this change in 0.2.

**Comment by libremente** [comment]
Switch to BCP 47 made in #40.
